Porfolio mobile size header and headline sections
momo-87/my-porfolio-project pull request #1
Opened 2023-03-23 17:43 UTC by Momo-87

2023-03-23 18:13 UTC, mahbubul14 requested changes
Hi @Momo-87,

Good job so far! :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

# Required Changes ♻️

- [ ] Pull Request should have a short summary describing introduced changes in more detail. Please work on it.
![pr](https://user-images.githubusercontent.com/70483835/227307257-df22e838-e9f2-41ad-ba39-1a669dcbfe15.png)


- [ ] Kindly check the inline comments under the review. :arrow_down: 

###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Proper Github flow used.

### Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

* N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-03-23 18:13 UTC, mahbubul14 commented on index.html
> +        </div>
- [ ] The `My Logo` text is on the left and should have a link (a tag). :+1:

2023-03-23 18:13 UTC, mahbubul14 commented on index.html
> +        </div>
- [ ] The hamburger button is on the right and should have a nav tag. The `nav` tag is for semantics reasons and the right position for convention and user experience for mobile devices. :+1:

2023-03-23 18:13 UTC, mahbubul14 commented on index.html
> +        </div>
- [ ] The main title (e.g., "I'm Marianne ...") should be in a `h1` tag. If you want that google (and other search engines) to know about a specific topic, in this case, you, use an h1 tag. Check [this link](https://www.reliablesoft.net/h1-tag/) for more info.

2023-03-23 18:13 UTC, mahbubul14 commented on index.html
> +        </div>
- [ ] The list of icons should use a `ul` tag to group them, and `li` per icon; each icon has a link (a tag). Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using href. Kindly work on it. :+1:

2023-03-24 07:25 UTC, amejid approved these changes
Hi @Momo-87, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Linter checks passing :heavy_check_mark: 
- Correct use of Github flow :heavy_check_mark: 
- Good UI design :heavy_check_mark: 
- Good semantic structure :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 07:39 UTC, merged